### PR TITLE
Add season and episode_or_date template substitutions

### PR DESCRIPTION
**Pull request by kankaristo**
Added 2 new template substitutions:
- `season_dir`: Adds e.g. `Season 04/` to the title, so that episodes can be put into directories. If the video does not have a season number, this results in an empty string.
- `episode_or_date`: This is the same as `episode` if the video has that available, or otherwise the same as `date`.

### CODE REVIEW

**Review by aajanki — CHANGES_REQUESTED** [review]
The episode_or_date feature is a good addition, but I have some concerns regarding the season_dir.

I'd rather not have the directory separator as a part of the substitution because that unnecessarily restricts how the token can be used. It would be more generic if there would be a "${season}" token with the substitution just "Season 01" (without the directory separator) and the user would add "/"  in the template where they choose, like this: `--output-template '${season}/${title}'`. The problem with this is that if season is empty, the output path would start with the root directory "/" accidentally, but that could be taken care of by removing leading slashes after the substitution step.

Another thing I'm not so fond of is having the English word "season" as part of the substitution, because somebody might then want to have the word in Finnish or Swedish, and that would complicate the code. How about some language-neutral substitution like "S01"?

Can you 
1. Replace `${season_dir}` with `${season}` that doesn't include the slash at the end, and
2. add a step at the end of TitleFormatter.format that removes leading slashes from the path, and
3. possibly also have it output "S01" instead of "Season 01"?

**Comment by kankaristo** [comment]
About "Season 01" vs "S01": the format "Season 01" is the most common for directory names (at least as far as I've seen), and e.g. Jellyfin *requires* that directory naming structure (with no way to configure it that I'm aware of).

And even "S01" isn't really "language-neutral". :P
In Finnish it should really be "K01" (which is what Yle Areena uses, although without the zero-padding).

I could add some way to configure the prefix? The default could be "S", or maybe an empty string, so that you could get a "plain" season number with `${season}`.

Any thoughts on how the configuration should be done (or if it's even a good idea)?
- A simple option would be a parameter, e.g. `--season-prefix="Season "`
- Or it could even be part of the template parameter, e.g. `${season=Season }`
    - Or if in the future some templates could use multiple parameters, something like `${season:prefix=Season ,suffix=...}` (but maybe that's feature-creep)

Or instead of configuring the prefix, it could be a template like `Season {}`, where the season number would be inserted. But then you have templates within templates, and if `{}` is missing, that's an error, etc., so maybe a simple prefix is better.

-----

The other things sound like good changes, I'll work on those soon (probably next weekend).

**Comment by aajanki** [comment]
After thinking a bit more, let's just keep it as "Season 01" after all. All the other options would increase the complexity too much to justify it.

**Comment by kankaristo** [comment]
Made the changes discussed above. Now `${season}/xyz` works identically to the earlier `${season_dir}xyz`.

**Review by aajanki — APPROVED** [review]
Thanks! Merging this now!

**Pull request merged**
