### PR TITLE
Add Python 3 to Travis CI

### PR DESCRIPTION
**Pull request by hugovk**
And Unicode fixes so pyflakes passes on the CI.

Also some pep8 fixes.

### CODE REVIEW

**Comment by aajanki** [comment]
Thanks for the patch. I'll merge this except for the unicode changes. They break yle-dl on Python 2.

**Comment by aajanki** [comment]
I realised that leaving the unicode keywords in the code means that I have to disable Python 3 on Travis.

**Comment by hugovk** [comment]
Do you have an example that breaks on Python 2 with the Unicode changes?

**Comment by aajanki** [comment]
Even `yle-dl --help` will fail with

```
Traceback (most recent call last):
  File "yle-dl", line 2031, in <module>
    main()
  File "yle-dl", line 2002, in main
    usage()
  File "yle-dl", line 107, in usage
    splashscreen()
  File "yle-dl", line 100, in splashscreen
    version)
  File "yle-dl", line 93, in log
    sys.stderr.write(msg.encode(enc, 'backslashreplace'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 56: ordinal not in range(128)
```

Also, parsing arguments fails: `yle-dl http://areena.yle.fi/1-3261432`

```
Traceback (most recent call last):
  File "yle-dl", line 2031, in <module>
    main()
  File "yle-dl", line 1923, in main
    argv = [str(x, encoding, 'ignore') for x in sys.argv[1:]]
TypeError: str() takes at most 1 argument (3 given)
```

**Comment by hugovk** [comment]
I had run yle-dl after making these changes, and it worked, but have just realised I'd accidentally run the system-install yle-dl and not the modified one. Whoops! So clearly the CI can also be improved to run the code, at least somewhat, and here's a PR: https://github.com/aajanki/yle-dl/pull/92

**Pull request merged**
